baseURL = "https://dwalkr.github.io/sawmill/"
languageCode = "en-us"
theme = "sawmill"
title = "Sawmill"
[Author]
name = "DJ Walker"
[params]
logo = "/logo.svg"

[[menu.main]]
    name = "View on Github"
    url = "https://github.com/dwalkr/sawmill"
    weight = 10